on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-node@v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version: 18
      - name: Build kintone plugin
        if: ${{ steps.release.outputs.release_created }}
        run: |
          npm ci && npm install @kintone/plugin-packer
          cd src && npx kintone-plugin-packer --ppk ./private.ppk --out ./mypluginname-ver${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}.plugin.zip .
      - name: Upload kintone plugin
        if: ${{ steps.release.outputs.release_created }}
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ steps.release.outputs.tag_name }} ./mypluginname-ver${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}.plugin.zip
