on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          release-type: node
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
      # - uses: actions/checkout@v4
      # - name: Update manifest.json
      #   run: |
      #     ls
      #     pwd
      #     ls src
      #     ls ./src/manifest.json
      #     jq '.version="0.2.0"' ./src/manifest.json > ./src/manifest.json.tmp && mv ./src/manifest.json.tmp ./src/manifest.json