on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
      # - uses: actions/checkout@v4
      #   # these if statements ensure that a publication only occurs when
      #   # a new release is created:
      #   if: ${{ steps.release.outputs.release_created }}
      # - name: Update manifest.json
      #   run: echo "`jq '.version="0.1.0"' src/manifest.json`" > src/manifest.json
      # - name: read manifest.json
      #   run: cat src/manifest.json